# Villagers Names Configuration file
# Created by Mancdev.com

#
# Enable to show villager names without hovering over them
name_visible: true

#
# Potential chance that a villager will have a custom name
# (1.0 = 100% chance of spawning with name)
# (0.45 = 45% chance of spawning with name)
name_potential: 0.45

#
# Full display names for Villager
display_name: "%custom_name%"
display_name_with_profession: "%custom_name% The %profession%"

#
# List of villager names
# ChatColor formatting: https://minecraft.gamepedia.com/Formatting_codes
# i.e. - "&c Jacob" will be displayed as red
villager_names:
  - "Merek"
  - "Merek"
  - "Carac"
  - "Ulric"
  - "Tybalt"
  - "Borin"
  - "Sadon"
  - "Terrowin"
  - "Rowan"
  - "Forthwind"
  - "Althalos"
  - "Fendrel"
  - "Brom"
  - "Hadrian"
  - "Lord"
  - "Walter"
  - "Earl"
  - "Sir"
  - "Oliver"
  - "Justice"
  - "Roger"
  - "Joseph"
  - "Geoffrey"
  - "William"
  - "Francis"
  - "Simon"
  - "John"
  - "Edmund"
  - "Charles"
  - "Benedict"
  - "Gregory"
  - "Peter"
  - "Henry"
  - "Frederick"
  - "Thomas"
  - "Arthur"
  - "Bryce"
  - "Donald"
  - "Leofrick"
  - "Letholdus"
  - "Lief"
  - "Barda"
  - "Rulf"
  - "Robin"
  - "Gavin"
  - "Terryn"
  - "Ronald"
  - "Jarin"
  - "Cassius"
  - "Leo"
  - "Cedric"
  - "Peyton"
  - "Josef"
  - "Janshai"
  - "Doran"
  - "Asher"
  - "Quinn"
  - "Zane"
  - "Xalvador"
  - "Favian"
  - "Destrian"
  - "Dain"
  - "Berinon"
  - "Tristan"
  - "Gorvenal"
  - "Millicent"
  - "Alys"
  - "Ayleth"
  - "Anastas"
  - "Alianor"
  - "Cedany"
  - "Ellyn"
  - "Helewys"
  - "Malkyn"
  - "Peronell"
  - "Sybbyl"
  - "Ysmay"
  - "Thea"
  - "Jacquelyn"
  - "Amelia"
  - "Gloriana"
  - "Good"
  - "Catherine"
  - "Anne"
  - "Mary"
  - "Arabella"
  - "Elizabeth"
  - "Hildegard"
  - "Brunhild"
  - "Adelaide"
  - "Alice"
  - "Beatrix"
  - "Cristiana"
  - "Eleanor"
  - "Emeline"
  - "Isabel"
  - "Juliana"
  - "Margaret"
  - "Matilda"
  - "Mirabelle"
  - "Rose"
  - "Helena"
  - "Guinevere"
  - "Isolde"
  - "Maerwynn"
  - "Muriel"
  - "Winifred"
  - "Godiva"
  - "Catrain"
  - "Angmar"
  - "Gussalen"
  - "Jasmine"
  - "Josselyn"
  - "Maria"
  - "Victoria"
  - "Gwendolynn"
  - "Enndolynn"
  - "Janet"
  - "Luanda"
  - "Krea"
  - "Rainydayas"
  - "Atheena"
  - "Dimia"
  - "Phrowenia"
  - "Aleida"
  - "Ariana"
  - "Alexia"
  - "Katelyn"
  - "Katrina"
  - "Loreena"
  - "Kaylein"
  - "Seraphina"
  - "Duraina"
  - "Ryia"
  - "Farfelee"
  - "Iseult"
  - "Brangian"
  - "Elspeth"
  - "&6James"
  - "&6Daniel"

#
# Keep disabled if you are not sure what this is?
debug: false