name: VillagerNames
version: 1.1
author: Mancdev
main: com.mancdev.vnames.VillagerNames
website: https://mancdev.com
commands:
  va:
    description: VillagerNames plugin help
    usage: /<command>
    permission: villagernames.help
    aliases: [va, villagernames]